source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'rails_config'
gem 'sqlite3'
gem 'rubyzip', :git => 'git://github.com/rubyzip/rubyzip.git', :require => 'zip'
gem 'nokogiri'
gem 'rmagick', :require => 'RMagick'
gem 'listen'
gem 'daemons'
gem 'rb-fsevent'
